"""Report Generator - Creates HTML and Markdown reports"""

import os
import json
from datetime import datetime
from typing import List, Dict, Any

from narrative_detector import Narrative


class ReportGenerator:
    """Generates beautiful reports in HTML and Markdown formats"""
    
    def __init__(self, output_dir: str = "output"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
    
    def generate_markdown(self, narratives: List[Narrative], timestamp: datetime = None) -> str:
        """Generate a markdown report"""
        timestamp = timestamp or datetime.now()
        
        md = []
        md.append("# 🔮 Solana Narrative Radar Report")
        md.append(f"\n**Generated:** {timestamp.strftime('%Y-%m-%d %H:%M UTC')}")
        md.append(f"\n**Period:** Past 14 days")
        md.append(f"\n**Total Signals Analyzed:** {sum(len(n.signals) for n in narratives)}")
        md.append("\n---\n")
        
        # Executive Summary
        md.append("## 📊 Executive Summary\n")
        md.append("The following narratives are emerging in the Solana ecosystem based on signals from GitHub, KOL activity, and market research:\n")
        
        for i, narrative in enumerate(narratives, 1):
            strength_bar = "█" * int(narrative.strength_score / 10) + "░" * (10 - int(narrative.strength_score / 10))
            md.append(f"{i}. **{narrative.name}** [{strength_bar}] {narrative.strength_score:.0f}/100")
        
        md.append("\n---\n")
        
        # Detailed Narratives
        for narrative in narratives:
            md.append(f"## {self._get_emoji(narrative.category)} {narrative.name}")
            md.append(f"\n**Strength Score:** {narrative.strength_score:.0f}/100 | **Signals:** {len(narrative.signals)}\n")
            
            # Summary
            md.append(self._generate_narrative_summary(narrative))
            
            # Evidence
            if narrative.evidence:
                md.append("\n### 🔍 Key Evidence")
                for ev in narrative.evidence[:5]:
                    md.append(f"- {ev}")
            
            # Build Ideas
            if narrative.build_ideas:
                md.append("\n### 💡 Build Ideas")
                for idea in narrative.build_ideas[:3]:
                    md.append(f"\n#### {idea['name']}")
                    md.append(f"\n{idea['description']}")
                    md.append(f"\n- **Tech Stack:** {', '.join(idea['tech_stack'])}")
                    md.append(f"- **Difficulty:** {idea['difficulty'].title()}")
                    md.append(f"- **Time to Build:** {idea['time_to_build']}")
                    md.append(f"- **Revenue Model:** {idea['potential_revenue']}")
                    md.append(f"- **Why Now:** {idea['why_now']}")
            
            # Top Signals
            md.append("\n### 📡 Top Signals")
            for signal in narrative.signals[:5]:
                source_icon = "🐙" if signal.source == "github" else "📰"
                md.append(f"- {source_icon} [{signal.title}]({signal.url})")
            
            md.append("\n---\n")
        
        # Action Plan
        md.append("## 🚀 Recommended Action Plan\n")
        md.append("Based on narrative strength and build opportunity analysis:\n")
        
        if narratives:
            top = narratives[0]
            md.append(f"1. **Highest Priority:** Focus on {top.name} - strongest signal with clearest opportunity")
            if top.build_ideas:
                md.append(f"   - Start with: {top.build_ideas[0]['name']}")
        
        if len(narratives) > 1:
            second = narratives[1]
            md.append(f"2. **Secondary Focus:** {second.name} - strong momentum, good market timing")
        
        md.append("\n3. **Monitor:** Keep watching infrastructure upgrades (Firedancer/Alpenglow) for timing")
        md.append("4. **Avoid:** Oversaturated meme coin tools without differentiation")
        
        # Footer
        md.append("\n---\n")
        md.append("*Report generated by Solana Narrative Radar*")
        md.append(f"\n*Data sources: GitHub API, Brave Search, Ecosystem Research*")
        
        return "\n".join(md)
    
    def generate_html(self, narratives: List[Narrative], timestamp: datetime = None) -> str:
        """Generate an HTML dashboard report"""
        timestamp = timestamp or datetime.now()
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Solana Narrative Radar</title>
    <style>
        :root {{
            --sol-purple: #9945FF;
            --sol-green: #14F195;
            --sol-blue: #00D1FF;
            --bg-dark: #0a0a0a;
            --bg-card: #1a1a1a;
            --text-primary: #ffffff;
            --text-secondary: #a0a0a0;
        }}
        
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        
        body {{
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
            background: var(--bg-dark);
            color: var(--text-primary);
            line-height: 1.6;
            padding: 20px;
        }}
        
        .container {{
            max-width: 1200px;
            margin: 0 auto;
        }}
        
        header {{
            text-align: center;
            padding: 40px 20px;
            background: linear-gradient(135deg, var(--sol-purple) 0%, var(--sol-blue) 100%);
            border-radius: 16px;
            margin-bottom: 30px;
        }}
        
        h1 {{
            font-size: 2.5rem;
            margin-bottom: 10px;
        }}
        
        .subtitle {{
            font-size: 1.1rem;
            opacity: 0.9;
        }}
        
        .meta {{
            display: flex;
            justify-content: center;
            gap: 30px;
            margin-top: 20px;
            font-size: 0.9rem;
        }}
        
        .meta-item {{
            background: rgba(255,255,255,0.1);
            padding: 8px 16px;
            border-radius: 20px;
        }}
        
        .narratives-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }}
        
        .narrative-card {{
            background: var(--bg-card);
            border-radius: 12px;
            padding: 24px;
            border: 1px solid #333;
            transition: transform 0.2s, border-color 0.2s;
        }}
        
        .narrative-card:hover {{
            transform: translateY(-4px);
            border-color: var(--sol-purple);
        }}
        
        .narrative-header {{
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 16px;
        }}
        
        .narrative-title {{
            font-size: 1.2rem;
            font-weight: 600;
            color: var(--sol-green);
        }}
        
        .strength-badge {{
            background: linear-gradient(135deg, var(--sol-purple), var(--sol-blue));
            padding: 4px 12px;
            border-radius: 12px;
            font-size: 0.85rem;
            font-weight: 600;
        }}
        
        .strength-bar {{
            height: 8px;
            background: #333;
            border-radius: 4px;
            overflow: hidden;
            margin: 12px 0;
        }}
        
        .strength-fill {{
            height: 100%;
            background: linear-gradient(90deg, var(--sol-green), var(--sol-blue));
            border-radius: 4px;
            transition: width 0.5s ease;
        }}
        
        .evidence-list {{
            margin: 16px 0;
        }}
        
        .evidence-item {{
            font-size: 0.9rem;
            color: var(--text-secondary);
            padding: 4px 0;
            border-left: 2px solid var(--sol-purple);
            padding-left: 12px;
            margin: 8px 0;
        }}
        
        .ideas-section {{
            margin-top: 20px;
            padding-top: 20px;
            border-top: 1px solid #333;
        }}
        
        .idea {{
            background: rgba(153, 69, 255, 0.1);
            border-radius: 8px;
            padding: 16px;
            margin: 12px 0;
        }}
        
        .idea-name {{
            font-weight: 600;
            color: var(--sol-blue);
            margin-bottom: 8px;
        }}
        
        .idea-desc {{
            font-size: 0.9rem;
            color: var(--text-secondary);
        }}
        
        .idea-meta {{
            display: flex;
            flex-wrap: wrap;
            gap: 8px;
            margin-top: 12px;
        }}
        
        .idea-tag {{
            background: rgba(20, 241, 149, 0.2);
            color: var(--sol-green);
            padding: 4px 10px;
            border-radius: 4px;
            font-size: 0.8rem;
        }}
        
        .signals-section {{
            margin-top: 16px;
        }}
        
        .signal {{
            display: block;
            color: var(--text-secondary);
            font-size: 0.85rem;
            padding: 6px 0;
            text-decoration: none;
            border-bottom: 1px solid #222;
        }}
        
        .signal:hover {{
            color: var(--sol-green);
        }}
        
        .signal-source {{
            display: inline-block;
            width: 20px;
        }}
        
        footer {{
            text-align: center;
            padding: 30px;
            color: var(--text-secondary);
            font-size: 0.9rem;
        }}
        
        .action-plan {{
            background: linear-gradient(135deg, rgba(153,69,255,0.2), rgba(0,209,255,0.2));
            border-radius: 12px;
            padding: 30px;
            margin: 30px 0;
        }}
        
        .action-plan h2 {{
            margin-bottom: 20px;
        }}
        
        .action-item {{
            background: var(--bg-card);
            border-radius: 8px;
            padding: 16px;
            margin: 12px 0;
            border-left: 3px solid var(--sol-green);
        }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🔮 Solana Narrative Radar</h1>
            <p class="subtitle">Emerging trends and build opportunities in the Solana ecosystem</p>
            <div class="meta">
                <span class="meta-item">📅 {timestamp.strftime('%Y-%m-%d %H:%M UTC')}</span>
                <span class="meta-item">📊 {sum(len(n.signals) for n in narratives)} signals analyzed</span>
                <span class="meta-item">🔥 {len(narratives)} active narratives</span>
            </div>
        </header>
        
        <div class="narratives-grid">
"""
        
        for narrative in narratives:
            emoji = self._get_emoji(narrative.category)
            html += f"""
            <div class="narrative-card">
                <div class="narrative-header">
                    <span class="narrative-title">{emoji} {narrative.name}</span>
                    <span class="strength-badge">{narrative.strength_score:.0f}/100</span>
                </div>
                <div class="strength-bar">
                    <div class="strength-fill" style="width: {narrative.strength_score}%"></div>
                </div>
                <p style="color: var(--text-secondary); font-size: 0.9rem;">{len(narrative.signals)} signals detected</p>
                
                <div class="evidence-list">
                    <strong style="font-size: 0.85rem; color: var(--sol-purple);">Key Evidence:</strong>
"""
            for ev in narrative.evidence[:3]:
                html += f'                    <div class="evidence-item">{ev}</div>\n'
            
            html += """                </div>
                
                <div class="ideas-section">
                    <strong style="color: var(--sol-blue);">💡 Top Build Ideas:</strong>
"""
            for idea in narrative.build_ideas[:2]:
                html += f"""
                    <div class="idea">
                        <div class="idea-name">{idea['name']}</div>
                        <div class="idea-desc">{idea['description'][:150]}...</div>
                        <div class="idea-meta">
                            <span class="idea-tag">{idea['difficulty'].title()}</span>
                            <span class="idea-tag">{idea['time_to_build']}</span>
                        </div>
                    </div>
"""
            
            html += """                </div>
                
                <div class="signals-section">
                    <strong style="font-size: 0.85rem;">📡 Recent Signals:</strong>
"""
            for signal in narrative.signals[:3]:
                icon = "🐙" if signal.source == "github" else "📰"
                title = signal.title[:50] + "..." if len(signal.title) > 50 else signal.title
                html += f'                    <a href="{signal.url}" class="signal" target="_blank"><span class="signal-source">{icon}</span> {title}</a>\n'
            
            html += """                </div>
            </div>
"""
        
        html += """
        </div>
        
        <div class="action-plan">
            <h2>🚀 Recommended Action Plan</h2>
"""
        if narratives:
            top = narratives[0]
            html += f"""
            <div class="action-item">
                <strong>1. Highest Priority:</strong> Focus on {top.name}<br>
                <span style="color: var(--text-secondary);">Strongest signal with clearest opportunity</span>
"""
            if top.build_ideas:
                html += f'<br><span style="color: var(--sol-green);">→ Start with: {top.build_ideas[0]["name"]}</span>'
            html += "</div>\n"
            
            if len(narratives) > 1:
                second = narratives[1]
                html += f"""
            <div class="action-item">
                <strong>2. Secondary Focus:</strong> {second.name}<br>
                <span style="color: var(--text-secondary);">Strong momentum, good market timing</span>
            </div>
"""
        
        html += """
            <div class="action-item">
                <strong>3. Monitor:</strong> Keep watching infrastructure upgrades (Firedancer/Alpenglow) for timing
            </div>
            <div class="action-item">
                <strong>4. Avoid:</strong> Oversaturated meme coin tools without differentiation
            </div>
        </div>
        
        <footer>
            <p>Report generated by Solana Narrative Radar</p>
            <p>Data sources: GitHub API, Brave Search, Ecosystem Research</p>
        </footer>
    </div>
</body>
</html>
"""
        return html
    
    def _get_emoji(self, category: str) -> str:
        """Get emoji for narrative category"""
        emojis = {
            "ai_agents": "🤖",
            "infrastructure": "🏗️",
            "stablecoins_payfi": "💵",
            "rwa_tokenization": "🏦",
            "mobile_consumer": "📱",
            "depin": "🌐",
            "memecoins": "🐸",
            "defi_evolution": "💱",
            "zk_compression": "🔐"
        }
        return emojis.get(category, "📊")
    
    def _generate_narrative_summary(self, narrative: Narrative) -> str:
        """Generate a summary paragraph for a narrative"""
        summaries = {
            "ai_agents": "AI agents are transforming Solana DeFi with autonomous trading capabilities. ai16z's framework and Solana Agent Kit with 60+ pre-built actions are enabling a new wave of intelligent on-chain applications.",
            "infrastructure": "Major infrastructure upgrades are positioning Solana as a 'Decentralized Nasdaq'. Firedancer targets 1M TPS while Alpenglow promises 150ms finality - both launching in 2026.",
            "stablecoins_payfi": "Stablecoin activity is exploding with $4.25B USDC on Solana. Western Union's USDPT and Visa settlement signal institutional adoption of Solana for payments.",
            "rwa_tokenization": "Real-world asset tokenization is gaining massive traction. Ondo's 200+ tokenized stocks and WisdomTree's expansion push RWA on Solana past $1B.",
            "mobile_consumer": "Mobile Web3 is becoming reality with Solana Seeker. 150K+ preorders and hardware-gated airdrops signal a new distribution model for consumer apps.",
            "depin": "DePIN (Decentralized Physical Infrastructure) continues to grow with projects like Dawn Network, Render, and Helium leveraging Solana's speed.",
            "memecoins": "Meme coin activity remains strong with Pump.fun processing 39K token launches daily and $180M in launchpad volume.",
            "defi_evolution": "DeFi protocols are evolving with new primitives around intents, liquid staking, and cross-protocol coordination.",
            "zk_compression": "ZK Compression enables 1000x cost reduction for on-chain state, unlocking new possibilities for NFTs and tokens."
        }
        return summaries.get(narrative.category, f"This narrative is showing strong signals in the Solana ecosystem.")
    
    def save_reports(self, narratives: List[Narrative]) -> Dict[str, str]:
        """Save both HTML and Markdown reports"""
        timestamp = datetime.now()
        
        # Generate reports
        md_content = self.generate_markdown(narratives, timestamp)
        html_content = self.generate_html(narratives, timestamp)
        
        # Save files
        md_path = os.path.join(self.output_dir, "narrative_report.md")
        html_path = os.path.join(self.output_dir, "narrative_report.html")
        
        with open(md_path, "w") as f:
            f.write(md_content)
        
        with open(html_path, "w") as f:
            f.write(html_content)
        
        # Also save JSON data
        json_path = os.path.join(self.output_dir, "narrative_data.json")
        with open(json_path, "w") as f:
            json.dump({
                "timestamp": timestamp.isoformat(),
                "narratives": [n.to_dict() for n in narratives]
            }, f, indent=2)
        
        return {
            "markdown": md_path,
            "html": html_path,
            "json": json_path
        }


if __name__ == "__main__":
    from signal_fetcher import fetch_all_signals
    from narrative_detector import detect_narratives
    from idea_generator import generate_all_ideas
    
    # Full pipeline
    signals = fetch_all_signals()
    detector = detect_narratives(signals)
    top_narratives = detector.get_top_narratives()
    generate_all_ideas(top_narratives)
    
    # Generate reports
    generator = ReportGenerator()
    paths = generator.save_reports(top_narratives)
    
    print("\n=== REPORTS GENERATED ===")
    for format_type, path in paths.items():
        print(f"  {format_type}: {path}")
